export const COPY = {
  APP_NAME: "CodeLab",

  NAV: {
    PROBLEMS: "Problems",
    SUBMISSIONS: "Submissions",
    CONTESTS: "Contests",
    SETTINGS: "Settings",
    PROFILE: "Profile",
    LOGOUT: "Logout",
    LOGIN: "Login",
    REGISTER: "Register",
    MENU: "Menu",
    PROBLEM_LISTS: "My Lists",
  },

  HOME: {
    TITLE: "Problems",
    SUBTITLE: "Sharpen your skills with coding challenges",
    EMPTY: "No problems available yet.",
    SEARCH_PLACEHOLDER: "Search problems...",
    FILTER_ALL: "All",
    SORT_NEWEST: "Newest",
    SORT_OLDEST: "Oldest",
    SORT_TITLE: "Title",
  },

  FILTERS: {
    DIFFICULTY: "Difficulty",
    TOPIC: "Topic",
    STATUS: "Status",
    EASY: "Easy",
    MEDIUM: "Medium",
    HARD: "Hard",
    ALL: "All",
  },

  LOGIN: {
    TITLE: "Welcome back",
    DESCRIPTION: "Sign in to continue",
    PROMPT: "Sign in to submit code",
    GATED_TITLE: "Authentication Required",
    GATED_DESCRIPTION:
      "Please sign in to access this content and track your progress.",
    ERROR: "Invalid username or password",
    SIGNING_IN: "Signing in...",
    SIGN_IN: "Sign in",
    NO_ACCOUNT: "Don't have an account?",
    REGISTER_LINK: "Register",
  },

  REGISTER: {
    TITLE: "Create an account",
    DESCRIPTION: "Start your coding journey",
    ERROR: "Registration failed",
    CREATING: "Creating account...",
    CREATE: "Create account",
    HAS_ACCOUNT: "Already have an account?",
    SIGN_IN_LINK: "Sign in",
    PASSWORD_MISMATCH: "Passwords do not match",
  },

  PLACEHOLDER: {
    USERNAME: "Enter your username",
    EMAIL: "Enter your email",
    PASSWORD: "Enter your password",
    CONFIRM_PASSWORD: "Confirm your password",
  },

  PROFILE: {
    TITLE: "Profile",
    SUBMISSIONS: "My Submissions",
    LOADING: "Loading profile...",
    USERNAME: "Username",
    EMAIL: "Email",
    JOINED: "Joined",
    NOT_AVAILABLE: "N/A",
    SKILL_MAP_TITLE: "Skill Map",
    SKILL_MAP_DESCRIPTION:
      "Skill tracking will be available after solving problems.",
    LOGIN_REQUIRED: "Please login to view your profile.",
    PROBLEM_LISTS_TITLE: "My Problem Lists",
    PROBLEM_LISTS_EMPTY: "You haven't created any problem lists yet.",
    CREATE_LIST: "Create New List",
    EDIT_LIST: "Edit List",
    DELETE_LIST: "Delete List",
    DELETE_CONFIRM_TITLE: "Delete List",
    DELETE_CONFIRM_MESSAGE: "Are you sure you want to delete this list? This action cannot be undone.",
    CANCEL: "Cancel",
    DELETE: "Delete",
    SAVE: "Save",
    SAVING: "Saving...",
    LIST_NAME: "List Name",
    LIST_NAME_PLACEHOLDER: "Enter list name",
    LIST_DESCRIPTION: "Description (optional)",
    LIST_DESCRIPTION_PLACEHOLDER: "Enter description",
  },

  PROBLEM: {
    NOT_FOUND: "Problem not found",
    LOADING: "Loading problem...",
    DESCRIPTION: "Description",
    EXAMPLES: "Examples",
    CONSTRAINTS: "Constraints",
    INPUT_FORMAT: "Input Format",
    OUTPUT_FORMAT: "Output Format",
    FOLLOW_UPS: "Follow-up",
    HINTS: "Hints",
    SOLUTION: "Solution",
    SAMPLE_INPUT: "Sample Input",
    SAMPLE_OUTPUT: "Sample Output",
    STDIN_PLACEHOLDER: "Enter input for testing...",
    RUN_CODE: "Run Code",
    RUNNING: "Running...",
    SUBMIT_CODE: "Submit",
    SUBMITTING: "Submitting...",
    SUBMIT: "Submit",
    RESULT: "Result",
    UNKNOWN_STATUS: "Unknown",
    STDOUT: "stdout",
    STDERR: "stderr",
    ERROR_PREFIX: "Error:",
    ALL_PASSED: "All Tests Passed!",
    SOME_PASSED: "Passed",
    FAILED: "Failed",
    TIME_LIMIT: "Time Limit",
    MEMORY_LIMIT: "Memory Limit",
    VIEW_SOLUTION: "View Solution",
    LOCKED_SOLUTION: "Sign in to view solution",
    AUTOSAVED: "Changes saved",
    SAVING: "Saving...",
    RESET_CODE: "Reset Code",
    RESET_CODE_CONFIRM: "Reset to default code?",
    MAXIMIZE_EDITOR: "Maximize Editor",
    RESTORE_LAYOUT: "Restore Layout",
    COLLAPSE_DESC: "Collapse Description",
    EXPAND_DESC: "Expand Description",
    UNSAVED: "Unsaved changes",
    KEYBOARD_SHORTCUTS: "Keyboard Shortcuts",
    SHORTCUT_RUN: "Run Code",
    SHORTCUT_SUBMIT: "Submit Code",
    SHORTCUT_SAVE: "Save Code",
  },

  TOAST: {
    LOGIN_REQUIRED: "Sign in to continue",
    LOGIN_REQUIRED_DESC: "Please sign in to access this feature.",
    CODE_SUBMITTED: "Code Submitted",
    CODE_SUBMITTED_DESC: "Your solution is being evaluated.",
    ALL_TESTS_PASSED: "Congratulations!",
    ALL_TESTS_PASSED_DESC: "All test cases passed successfully.",
    TESTS_FAILED: "Tests Failed",
    TESTS_FAILED_DESC:
      "Some test cases did not pass. Check your output and try again.",
    CODE_SAVED: "Changes Saved",
    CODE_SAVED_DESC: "Your code has been autosaved.",
    SESSION_EXPIRED: "Session Expired",
    SESSION_EXPIRED_DESC: "Please sign in again to continue.",
    NETWORK_ERROR: "Connection Error",
    NETWORK_ERROR_DESC:
      "Unable to connect. Please check your internet connection.",
  },

  SUBMISSIONS: {
    TITLE: "Submissions",
    EMPTY: "No submissions yet",
    STATUS: "Status",
    LANGUAGE: "Language",
    TIME: "Time",
    MEMORY: "Memory",
    DATE: "Submitted",
    REVERT: "View",
    RE_SUBMIT: "Resubmit",
  },

  FORM_LABELS: {
    USERNAME: "Username",
    PASSWORD: "Password",
    CONFIRM_PASSWORD: "Confirm Password",
    EMAIL: "Email",
    STDIN: "stdin (optional)",
    CODE: "Code",
  },

  LANGUAGE_LABELS: {
    python3: "Python3",
    java: "Java",
    cpp: "C++",
    c: "C",
  },

  CODE_TEMPLATES: {
    python3: '# Write your code here\nprint("Hello World")\n',
    java: '// Write your code here\npublic class Main {\n    public static void main(String[] args) {\n        System.out.println("Hello World");\n    }\n}\n',
    cpp: '// Write your code here\n#include <iostream>\nusing namespace std;\n\nint main() {\n    cout << "Hello World" << endl;\n    return 0;\n}\n',
    c: '// Write your code here\n#include <stdio.h>\n\nint main() {\n    printf("Hello World\\n");\n    return 0;\n}\n',
  },

  ACCESSIBILITY: {
    OPEN_MENU: "Open menu",
    CLOSE_MENU: "Close menu",
    TOGGLE_THEME: "Toggle theme",
    NAVIGATE_PROBLEM: "Go to problem",
  },
} as const;
