"""change_submission_hint_to_use_submission_id

Revision ID: 625a6ddab953
Revises: 18b2552e7116
Create Date: 2026-05-03 23:53:38.007126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '625a6ddab953'
down_revision: Union[str, Sequence[str], None] = '18b2552e7116'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission_hints', sa.Column('submission_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('uq_submission_hints_user_problem'), 'submission_hints', type_='unique')
    op.create_unique_constraint(None, 'submission_hints', ['submission_id'])
    op.drop_constraint(op.f('submission_hints_problem_id_fkey'), 'submission_hints', type_='foreignkey')
    op.create_foreign_key(None, 'submission_hints', 'submissions', ['submission_id'], ['id'], ondelete='CASCADE')
    op.drop_column('submission_hints', 'problem_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission_hints', sa.Column('problem_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'submission_hints', type_='foreignkey')
    op.create_foreign_key(op.f('submission_hints_problem_id_fkey'), 'submission_hints', 'problems', ['problem_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'submission_hints', type_='unique')
    op.create_unique_constraint(op.f('uq_submission_hints_user_problem'), 'submission_hints', ['user_id', 'problem_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('submission_hints', 'submission_id')
    # ### end Alembic commands ###
