export const ROUTES = {
  HOME: "/",
  PROBLEM_DETAIL: "/problems/:slug",
  problemDetail: (slug: string) => `/problems/${slug}`,
  SUBMISSIONS: "/submissions",
  LOGIN: "/login",
  REGISTER: "/register",
  FORGOT_PASSWORD: "/forgot-password",
  PROFILE: "/profile",
  PROBLEM_LISTS: "/problem-lists",
  problemLists: () => "/problem-lists",
  PROBLEM_LIST_DETAIL: "/problem-lists/:id",
  problemListDetail: (id: number) => `/problem-lists/${id}`,
  ADMIN_ROOT: "/admin",
  ADMIN_PROBLEMS: "/admin/problems",
  ADMIN_PROBLEM_CREATE: "/admin/problems/create",
  ADMIN_PROBLEM_EDIT: "/admin/problems/:id/edit",
  adminProblemEdit: (id: number) => `/admin/problems/${id}/edit`,
  ADMIN_TOPICS: "/admin/topics",
  ADMIN_USERS: "/admin/users",
  ADMIN_SUBMISSIONS: "/admin/submissions",
} as const;
